# Copyright 2021 Netaddiction

{
    "name": "Netaddiction Theme Rewrite",
    "category": "eCommerce",
    "version": "14.0.2.42.0",
    "author": "Netaddiction",
    "license": "LGPL-3",
    "depends": [
        "portal",
        "product",
        "web",
        "website",
        "website_sale",
        "theme_clarico_vega",
        "odoo_website_wallet",
        "product_bundle_pack",
        "advance_website_all_in_one",
        "website_all_in_one",
        "product_template_tags",
        "wk_variant_search",
        "affiliate_management",
        "website_seo_pro",
        "website_sale_delivery",
        "payment",
        "netaddiction_special_offers",
    ],
    "data": [
        "templates/assets.xml",
        "templates/template_my_address.xml",
        "templates/template_my_portal.xml",
        "templates/template_my_orders.xml",
        "templates/template_my_payment_method.xml",
        "templates/template_category.xml",
        "templates/template_product.xml",
        "templates/template_privacy_policy.xml",
        "templates/template_shipping_terms.xml",
        "templates/template_tag.xml",
        "templates/template_wallet.xml",
        "templates/template_add_wallet_balance.xml",
        "templates/template_checkout.xml",
        "templates/template_checkout_address.xml",
        "templates/social_sidebar.xml",
        "templates/template_account.xml",
        "templates/custom_product_label.xml",
        "templates/page_404.xml",
        "templates/template_orders.xml",
        "templates/template_affiliate.xml",
        "templates/template_affiliate_home.xml",
        "templates/template_affiliate_report.xml",
        "templates/template_affiliate_tools.xml",
        "templates/template_affiliate_orders.xml",
        "templates/template_affiliate_traffic.xml",
        "templates/template_affiliate_payments.xml",
        "templates/affiliate_menu.xml",
        "templates/login.xml",
        "templates/wallet_custom_parts.xml",
        "templates/google-snippet/product.xml",
        "templates/category_menu.xml",
        "templates/filters.xml",
    ],
    # Technical
    "installable": True,
}
